FROM node:lts-alpine AS packages
WORKDIR /lebobeautyco/packages

COPY ./packages /lebobeautyco/packages

# Install dependencies for all internal packages
RUN set -e && \
  find ./ -mindepth 1 -maxdepth 1 -type d \
  -exec sh -c 'for dir; do \
    if [ -f "$dir/package.json" ]; then \
      echo "Installing dependencies in $dir"; \
      npm --prefix "$dir" install; \
    fi; \
  done' _ {} +


FROM node:lts-alpine AS frontend
WORKDIR /lebobeautyco/frontend

COPY ./frontend/package*.json ./
RUN npm install --force && npm cache clean --force

COPY ./frontend ./ 
COPY ./frontend/.env.docker.development .env

# Copy preinstalled internal packages
COPY --from=packages /lebobeautyco/packages /lebobeautyco/packages

EXPOSE 8006
CMD ["npm", "run", "dev:docker"]
